# Generated by Django 5.2.17 on 2026-10-04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
      ('confessions', '0001_initial'),
      migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
      migrations.RemoveField(
          model_name='confession',
          name='upvotes',
      ),
      migrations.CreateModel(
          name='Reaction',
          fields=[
              (
                  'id',
                  models.BigAutoField(
                      auto_created=True,
                      primary_key=True,
                      serialize=False,
                      verbose_name='ID',
                  ),
              ),
              (
                  'confession',
                  models.ForeignKey(
                      on_delete=django.db.models.deletion.CASCADE,
                      related_name='reactions',
                      to='confessions.confession',
                  ),
              ),
              (
                  'user',
                  models.ForeignKey(
                      on_delete=django.db.models.deletion.CASCADE,
                      related_name='confession_reactions',
                      to=settings.AUTH_USER_MODEL,
                  ),
              ),
          ],
          options={
              'constraints': [
                  models.UniqueConstraint(
                      fields=('user', 'confession'),
                      name='unique_user_confession_reaction',
                  ),
              ],
          },
      ),
  ]
